### ISSUE TITLE
Center download icon

### ISSUE THREAD

**Issue by ehrro** [sunstar-foundation/sunstar-foundation#20]
![image](https://github.com/sunstar-foundation/sunstar-foundation/assets/1226479/9bcd0597-4dbc-481a-9e93-01031885ceae)

:download: and :download-white:

@bosschaert @sdmcraft 

Not a blocker

**Comment by jindaliiita** [comment]
@ehrro Can you specify any page for this ?

**Comment by ehrro** [comment]
Sorry @jindaliiita forgot to add the url:
https://main--sunstar-foundation--sunstar-foundation.hlx.page/dentistry/adult
