### ISSUE TITLE
A page with a name of document has been deleted

### ISSUE THREAD

**Issue by ehrro** [sunstar-foundation/sunstar-foundation#23]
The word document under education folder called document.docx doesn't exist anymore.

I looked inside the trash but couldn't find it.

Can you please check if you have it copied somewhere?

https://main--sunstar-foundation--sunstar-foundation.hlx.live/for-healthcare-info/education/document

![image](https://github.com/sunstar-foundation/sunstar-foundation/assets/1226479/60505e63-6b17-4357-a83c-b40cc452dc2f)

@sdmcraft @jindaliiita @bosschaert

**Comment by JiangLong2019** [comment]
@ehrro Created a new page, please help to check.

https://main--sunstar-foundation--sunstar-foundation.hlx.live/for-healthcare-info/education/document
