### ISSUE TITLE
Dentistry header issue on mobile

### ISSUE THREAD

**Issue by ehrro** [sunstar-foundation/sunstar-foundation#37]
There is a small problem with the dentistry header on mobile:
![image](https://github.com/sunstar-foundation/sunstar-foundation/assets/1226479/31b300a8-710a-459b-b9a2-92127fd80f44)

@bosschaert @sdmcraft @meejain

**Comment by meejain** [comment]
Sure. This is Ack'ed @ehrro  . Will keep this issue posted.
