### ISSUE TITLE
Videos not playing on Iphone

### ISSUE THREAD

**Issue by ehrro** [sunstar-foundation/sunstar-foundation#48]
We have the same issues with videos not playing on iphone on Sunstar Foundation website.

The videos integrated on that page are coming from AEM Assets.

https://www.sunstar-foundation.org/oral-care/school

Can you please fix it? Thanks.

@bosschaert @sdmcraft @JiangLong2019

**Comment by bosschaert** [comment]
@sdmcraft could you please take a look?

**Comment by sdmcraft** [comment]
I think this has already been addressed. @ehrro , could you please confirm?
