### ISSUE TITLE
Dentistry Header revamp

### ISSUE THREAD

**Issue by ehrro** [sunstar-foundation/sunstar-foundation#8]
Can you please enhance the dentistry site header?

1. The text next to the logo should be font-weight: normal, should have 32px (2rem) distance from the logo and should be standard blue color (same as the logo).
2. The text above the phone number should be smaller, should be standard blue color and should be positioned on top of the phone number (4px from the phone number).
3. The phone number should be in standard blue color.
4. The buttons should be 24px(1.5rem) from the phone number and the text size should be a bit smaller.

![image](https://github.com/sunstar-foundation/sunstar-foundation/assets/1226479/63eee6a0-6e37-4140-aabe-dfd8f112d403)

Not a blocker

@bosschaert @sdmcraft

**Comment by shrotia** [comment]
Page : https://main--sunstar-foundation--sunstar-foundation.hlx.live/dentistry
