### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by ehrro** [sunstar-foundation/sunstar-foundation#9]
Thank you Message missing. We don't get any feedback if the form is successfully submitted or not.

Additionally we are missing the __id__ entry in the incoming contact.xlsx file.
![image](https://github.com/sunstar-foundation/sunstar-foundation/assets/1226479/8df065fa-81cb-41fb-bb7b-be7dadb3c66e)
![image](https://github.com/sunstar-foundation/sunstar-foundation/assets/1226479/26844bcf-c747-4042-afe1-6509474fd4d8)

Can you make sure this works for both languages.

Thanks @bosschaert @sdmcraft @meejain @jindaliiita @shrotia

**Comment by meejain** [comment]
Discussion with @dejaneric  on the same - https://adobe-dx-support.slack.com/archives/C051MV16P0D/p1708081228703509

**Comment by meejain** [comment]
@dejaneric  - The Thank You message is working now for both https://main--sunstar-foundation--sunstar-foundation.hlx.page/contact-form & https://main--sunstar-foundation--sunstar-foundation.hlx.page/en/contact. Pl check & validate further. 

With regards to the addition of ID field to the form, just want to be clear on that - 

The original URL - https://www.sunstar-foundation.org/en/contact doesnt have any ID field. Are we just adding another entry to the form visible to the End User ?

**Comment by ehrro** [comment]
Hello @meejain,

The id is not visible to the end user. It's generated in the system and it's only used to handle the sending of emails from power automate.

You can copy the logic from sunstar.com or sunstar-engineering.com.

**Comment by meejain** [comment]
> Hello @meejain,
> 
> The id is not visible to the end user. It's generated in the system and it's only used to handle the sending of emails from power automate.
> 
> You can copy the logic from sunstar.com or sunstar-engineering.com.

Pl check now & validate the workflow for __id__ column 
- https://main--sunstar-foundation--sunstar-foundation.hlx.live/en/contact . Added __id__ to the sheet which seems automatically gets hidden from display.

**Comment by ehrro** [comment]
Works fine.
